source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'pg', '~> 0.18'
gem 'sass-rails', '~> 4.0.0'
gem 'bootstrap-sass'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :development, :test do
  gem 'pry'
end

group :test do
  gem 'rspec-rails'
  gem 'database_cleaner'
  gem 'capybara'
end
